version: '3'

services:
  portainer:
    image: portainer/portainer
    command: -H "tcp://tasks.portainer_agent:9001" --tlsskipverify
    restart: always
    ports:
    - 9000:9000
    networks: 
      - agent_network
    deploy:
      replicas: 1
      placement:
        constraints:
        - node.role == manager
    
networks:
  agent_network:
