debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":4443"
  [entryPoints.https.tls]

[retry]

[api]

[docker]
endpoint = "unix:///var/run/docker.sock"
# domain = "test1.dck.7i.de"
watch = true
exposedByDefault = false

[acme]
# caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
email = "webmaster@7i.de"
storage = "acme.json"
onDemand = false
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
entryPoint = "http"

[traefikLog]
filePath = "/traefik.log"

[accessLog]
filePath = "/access.log"
